change repo to develop in mac app

diff --git a/stochss-launcher/OSX/App/StochSS.app/Contents/Resources/script b/stochss-launcher/OSX/App/StochSS.app/Contents/Resources/script
--- a/stochss-launcher/OSX/App/StochSS.app/Contents/Resources/script
+++ b/stochss-launcher/OSX/App/StochSS.app/Contents/Resources/script
@@ -21,12 +21,12 @@ then
 	(docker-machine env stochss1-7 >> $DIR/.dockerlog)
 	eval "$(docker-machine env stochss1-7)" || { echo "Could not connect to VM successfully. Exiting..."; exit 1; }
 	DOCKERPATH=$(dirname $(which docker-machine))
-	
+
 	(more $DIR/.admin_key >> $DIR/.dockerlog 2>&1) || (echo `uuidgen` > $DIR/.admin_key && echo "Generated key.")
 	echo "Docker daemon is now running. The IP address of stochss1-7 VM is $(docker-machine ip stochss1-7)"
 	token=`more $DIR/.admin_key`
 	# Start container if it already exists, else run aviral/stochss-initial image to create a new one
-	docker start stochsscontainer1_7 >> $DIR/.dockerlog 2>&1 || { { docker images | grep "aviralcse/stochss-initial" | grep -oh "1.7" || { echo "A terminal window should open up to download StochSS. Waiting for image..." && osascript $DIR/StochSS.scpt $DOCKERPATH && { docker images | grep "aviralcse/stochss-initial" | grep -oh "1.7" || { echo "Failed to get image."; clean_up; exit 1; }; }; }; } && { first_time=true && docker run -d -p 8080:8080 -p 8000:8000 --name=stochsscontainer1_7 aviralcse/stochss-initial:1.7 sh -c "cd stochss-master; ./run.ubuntu.sh -a $(docker-machine ip stochss1-7) -t $token --yy" >> $DIR/.dockerlog && echo "Starting StochSS 1.7 for the first time."; } } || { echo "Failed to start server."; clean_up; exit 1; }
+	docker start stochsscontainer1_7 >> $DIR/.dockerlog 2>&1 || { { docker images | grep "aviralcse/stochss-initial" | grep -oh "1.7" || { echo "A terminal window should open up to download StochSS. Waiting for image..." && osascript $DIR/StochSS.scpt $DOCKERPATH && { docker images | grep "aviralcse/stochss-initial" | grep -oh "1.7" || { echo "Failed to get image."; clean_up; exit 1; }; }; }; } && { first_time=true && docker run -d -p 8080:8080 -p 8000:8000 --name=stochsscontainer1_7 aviralcse/stochss-initial:1.7 sh -c "cd stochss-develop; ./run.ubuntu.sh -a $(docker-machine ip stochss1-7) -t $token --yy" >> $DIR/.dockerlog && echo "Starting StochSS 1.7 for the first time."; } } || { echo "Failed to start server."; clean_up; exit 1; }
 
 	# test server is up and connect to it
 	echo "Starting server. This process may take up to 5 minutes..."
@@ -36,7 +36,7 @@ then
 	done
 	echo "StochSS server is running at the following URL. The browser window should open automatically."
 	echo "http://$(docker-machine ip stochss1-7):8080/login?secret_key=`echo $token`"
-	
+
 	open "http://$(docker-machine ip stochss1-7):8080/login?secret_key=`echo $token`"
 
 else
@@ -45,6 +45,6 @@ else
 fi
 
 while :
-do 
+do
 	sleep 10000
 done
