Updates for the .app for docker machine

diff --git a/stochss-launcher/OSX/App/StochSS__with_docker_machine.app/Contents/Resources/script b/stochss-launcher/OSX/App/StochSS__with_docker_machine.app/Contents/Resources/script
--- a/stochss-launcher/OSX/App/StochSS__with_docker_machine.app/Contents/Resources/script
+++ b/stochss-launcher/OSX/App/StochSS__with_docker_machine.app/Contents/Resources/script
@@ -2,7 +2,7 @@
 trap clean_up INT SIGHUP SIGINT SIGTERM
 
 STOCHSS_IMAGE_NAME="briandrawert/stochss-launcher"
-STOCHSS_CONTAINER_NAME="stochsscontainer1_8"
+STOCHSS_CONTAINER_NAME="stochsscontainer1_9"
 STOCHSS_VM_NAME="stochss1-9"
 STOCHSS_IMAGE_TAG="1.9"
 STOCHSS_VERSION="1.9"
@@ -15,8 +15,30 @@ function clean_up(){
 	IR="$( cd ~/.stochss; pwd )"
 	docker stop $STOCHSS_CONTAINER_NAME >> $IR/.dockerlog 2>&1
 	docker-machine stop $STOCHSS_VM_NAME || exit 1
-	echo "Done"
+	echo "StochSS stopped."
 	exit
+}
+
+function initialize_error_log(){
+    if [ ! -d ~/.stochss ]; then mkdir ~/.stochss; fi
+	DIR="$( cd ~/.stochss; pwd )"
+    echo `date` > $DIR/.dockerlog
+    echo `uname -a` >> $DIR/.dockerlog
+}
+
+function clean_up_and_show_error_log(){
+    echo
+    echo "Please wait while StochSS $STOCHSS_VERSION is stopped correctly..."
+    DIR="$( cd ~/.stochss; pwd )"
+	docker stop $STOCHSS_CONTAINER_NAME >> $DIR/.dockerlog 2>&1
+	docker-machine stop $STOCHSS_VM_NAME || exit 1
+    echo "StochSS stopped."
+    echo ""
+    echo ""
+    echo ""
+    echo "Error Log:"
+    echo `cat $DIR/.dockerlog`
+    exit
 }
 
 function create_container_and_try_again(){
@@ -24,7 +46,7 @@ function create_container_and_try_again(){
 	APPLE_SCRIPT_PAT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 	echo "Failed to get image."
 	docker ps -aq | grep "[a-z;0-9]" && docker rm `docker ps -aq`
-	docker rmi $STOCHSS_CONTAINER_NAME >> $DI/.dockerlog 2>&1
+	docker rmi $STOCHSS_IMAGE_NAME >> $DI/.dockerlog 2>&1
 	echo "Trying once more."
 	echo "Another terminal window should open up to download StochSS. Waiting for image..." && osascript $APPLE_SCRIPT_PAT/StochSS.scpt $(dirname $(which docker-machine))
 	return 0
@@ -32,7 +54,7 @@ function create_container_and_try_again(){
 
 if [[ $(uname -s) == 'Darwin' ]]
 then
-	if [ ! -d ~/.stochss ]; then mkdir ~/.stochss; fi
+    initialize_error_log
 	docker-machine version || { echo "Docker-machine not detected. Please read the installation instructions at xyz"; exit 1; }
 	DIR="$( cd ~/.stochss; pwd )"
 	APPLE_SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
@@ -47,6 +69,7 @@ then
 	echo "Docker daemon is now running. The IP address of $STOCHSS_VM_NAME VM is $(docker-machine ip $STOCHSS_VM_NAME)"
 	token=`more $DIR/.admin_key`
 	# Start container if it already exists, else run aviral/stochss-initial image to create a new one
+	echo "docker start $STOCHSS_CONTAINER_NAME" >> $DIR/.dockerlog 2>&1
 	if ! docker start $STOCHSS_CONTAINER_NAME >> $DIR/.dockerlog 2>&1 ; then
 	 	if ! docker images | grep "$STOCHSS_IMAGE_NAME" | grep -oh "STOCHSS_IMAGE_TAG" ; then
 			 echo "A terminal window should open up to download StochSS. Waiting for image..." && osascript $APPLE_SCRIPT_PATH/StochSS.scpt $DOCKERPATH
@@ -54,25 +77,28 @@ then
 					if [ "$try_again" == 'true' ]; then
 		 				if ! create_container_and_try_again ; then
 								echo "Failed to get image."
-								clean_up
+                                clean_up_and_show_error_log
 								exit 1
 						fi;
 					else
 						echo "Failed to get image."
-						clean_up
+                        clean_up_and_show_error_log
 						exit 1
 					fi;
 			 fi;
 			 first_time=true
 			 if ! docker images | grep "$STOCHSS_IMAGE_NAME" | grep -oh "$STOCHSS_IMAGE_TAG" ; then
 				 echo "Failed to get image."
-				 clean_up
+                 clean_up_and_show_error_log
 				 exit 1
 			 fi;
-			 if docker run -d -p 8080:8080 -p 9999:9999 --name=$STOCHSS_CONTAINER_NAME $STOCHSS_IMAGE_NAME:$STOCHSS_IMAGE_TAG sh -c "cd stochss-master; ./run.ubuntu.sh -a 0.0.0.0 -t $token --yy" >> $DIR/.dockerlog; then
+             echo "docker run -d -p 8080:8080 -p 8000:8000 -p 9999:9999 --name=$STOCHSS_CONTAINER_NAME $STOCHSS_IMAGE_NAME:$STOCHSS_IMAGE_TAG sh -c \"cd /stochss-master && export PYTHONPATH=/stochss-master/app/lib/:/usr/local/lib/python2.7/dist-packages:/stochss-master/sdk/python:/stochss-master/sdk/python/google:/stochss-master/sdk/python/lib && ./run.ubuntu.sh -t $token -a 0.0.0.0\"" >> $DIR/.dockerlog
+			 if docker run -d -p 8080:8080 -p 8000:8000 -p 9999:9999 --name=$STOCHSS_CONTAINER_NAME $STOCHSS_IMAGE_NAME:$STOCHSS_IMAGE_TAG sh -c "cd /stochss-master && export PYTHONPATH=/stochss-master/app/lib/:/usr/local/lib/python2.7/dist-packages:/stochss-master/sdk/python:/stochss-master/sdk/python/google:/stochss-master/sdk/python/lib && ./run.ubuntu.sh -t $token -a 0.0.0.0" >> $DIR/.dockerlog; then
 			    echo "Starting StochSS $STOCHSS_VERSION for the first time."
 			 else
-				 echo "Failed to start server."; clean_up; exit 1;
+				 echo "Failed to start server."
+                 clean_up_and_show_error_log
+                 exit 1
 			 fi;
 		fi;
 	fi;
@@ -89,7 +115,7 @@ then
 
 else
 	echo "This operating system is not recognized."
-	clean_up
+    clean_up_and_show_error_log
 fi
 
 while :
